### ISSUE TITLE
Nest 설치 및 Chat 모듈 구성

### ISSUE THREAD

**Issue by jae-hwan-kim** [Gaepo-transcendance-fighters/BACK-END#1]
## [ ✒️ Nest 설치 및 Chat 모듈 구성 ]
- [x] nest 앱 설치
- [x] chat 모듈 설치
- [x] .gitignore 설정

---

## [ 📄 상세 내용 ]
* nest 앱을 설치한다.
* chat Module, Controller, Service, Entity, Repository, Socket 구성한다.
* gitignore 를 설정한다.

**Comment by wochae** [comment]
CRUD , WebSocket installed,
