### ISSUE TITLE
MAIN_CHAT_0

### ISSUE THREAD

**Issue by jae-hwan-kim** [Gaepo-transcendance-fighters/BACK-END#10]
## [ ✒️ DM 존재 여부 확인 ]
* MAIN_CHAT_0
상대 프로필에서 DM 하기를 눌렀을 때, 상대와 메시지한 기록이 있는지 확인하는 API 를 구현한다.
- [x] GET 구현

---

## [ 📄 상세 내용 ]
* METHOD : GET
* URL : /chat/dm/:target_nickname
* request body
{
  my_nickname,
  target_nickname
}
* response body
{
  message[],
  channelName
}

**Comment by wochae** [comment]
channelMember 객체가 지금 반환되고 있습니다. 단 두 개
이거에서 해당 channelId 를 message 테이블에서 찾아서
Message 객체들과 channlName( Optional ) 을 반환해야 함

**Comment by jae-hwan-kim** [comment]
API 재설계로 해당 이슈 강제 종료.
