### ISSUE TITLE
게임에서 일어나는 버그

### ISSUE THREAD

**Issue by HiHoi** [Gaepo-transcendance-fighters/BACK-END#186]
---
name: 게임 버스
about: 버그를 보고할 때 사용하는 템플릿입니다.
title: '게임 버그'
labels: bug
assignees: 'hoslim'

---

## [ ✒️ 제목 ]

게임 연결 이후 일어나는 버그에 대한 이슈 입니다.

---

## [ 📄 상세 내용 ]

- [ ]

**Comment by wochae** [comment]
<img width="1366" alt="image" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/101040879/168cb632-fce6-4218-aaac-92b91fa4ffdd">

친선전 진행을 할 때, 처음 요청하는 사람 ( 이하 유저 1 )의 상대편 ( 이하 유저 2 )이 메시지를 받지 못하는 상황.
그 뒤에 유저 2가 처음 요청한 유저 1한테 친선전을 요청하면 그건 또 됨.
그래서 큐에 대기하고 있었는데 게임 진행이 되지 않고 있음.
유저 2가 메인으로 돌아갈 때, 문제가 없는데
유저 1이 메인우로 돌아갈 때, 저 사진 처럼 에러가 발생.
게임이 터지면 서버에 모든 서비스가 진행이 되지 않음.

**Comment by HiHoi** [comment]
스코어 부분 해결 했습니다. 단지 스코어는 먹히게 하는데 재시작을 못하네요 ㅠㅠ

```

  private checkHitTheGoalPost(
    ballData: [number, number],
    vector: Vector,
    engine: Physics,
  ): boolean {
    let ret: boolean;
    ret = false;
    if (vector === Vector.DOWNLEFT || vector === Vector.UPLEFT) {
      if (ballData[0] - 20 <= engine.MIN_WIDTH) {
        ballData[0] = engine.MIN_WIDTH + 20;
        ret = true;
      }
    } else if (vector === Vector.DOWNRIGHT || vector === Vector.UPRIGHT) {
      if (ballData[0] + 20 >= engine.MAX_WIDTH) {
        ballData[0] = engine.MAX_WIDTH - 20;
        ret = true;
      }
    }
    return ret;
  }
```

//수정 후
```

  private checkHitTheGoalPost(
    ballData: [number, number],
    vector: Vector,
    engine: Physics,
  ): boolean {
    let ret: boolean;
    ret = false;
    if (vector === Vector.DOWNLEFT || vector === Vector.UPLEFT) {
      if (ballData[0] - 20 <= engine.MIN_WIDTH) {
        ballData[0] = engine.MIN_WIDTH - 20;
        ret = true;
      }
    } else if (vector === Vector.DOWNRIGHT || vector === Vector.UPRIGHT) {
      if (ballData[0] + 20 >= engine.MAX_WIDTH) {
        ballData[0] = engine.MAX_WIDTH + 20;
        ret = true;
      }
    }
    return ret;
  }
```

**Comment by Paul2021-R** [comment]
친선전 API 문제 상황정리 
1. chat_invite_ask 
    1. myUserIdx: 0 문제 
<img width="967" alt="스크린샷 2023-09-14 오전 1 24 30" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/80471693/3bc9363d-bef8-41b8-88c6-eff5b62b478d">
		- myUserIdx: authState.userInfo.id, : 이 부분에서 userId가 정상적으로 설정이 안되어서 0이 들어옴, 따라서 서버에서 정상처리가 안됨. 
		- 해당 부분을 아래 사진 처럼 수정하니까, myUserIdx 가 정상적으로 들어오는데 chat_invite_answer가 정상적으로 받아짐. 

￼
<img width="668" alt="스크린샷 2023-09-14 오전 1 46 30" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/80471693/d4179d43-274a-4bb1-bde5-ae6aa9add90e">

		- 그러나 정상적으로 chat_invite_ask 를 보냈음에도, 받는 쪽이 정상적으로 소켓 이벤트 처리가 안됨
