### ISSUE TITLE
게임 진행 후 유저 테이블에 승패 수 반영

### ISSUE THREAD

**Issue by wochae** [Gaepo-transcendance-fighters/BACK-END#225]
---

## [ ✒️ 이번엔 Win... ]

---

## [ 📄 상세 내용 ]

- gameRecord, gameChannel 이상 무
- Users 테이블에 이긴 사람에 win 이 반영되지 않는다, 진 사람의 lose 는 반영

**Comment by Paul2021-R** [comment]
엥 디비 정상인디....

**Comment by wochae** [comment]
디비 유저테이블에 유저를 갱신할 때 인메모리 유저 객체로 저장하고 있어서
게임 결과 승패 추가하는 로직 뒤에 const user1, 2 로 추가한 유저들의 값이랑 
그 뒤에 인메모리 유저에 각 승패 값이랑 달라요

**Comment by wochae** [comment]
user1 : hoslim, user2 : wochae


<img width="470" alt="image" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/101040879/a0b73ea3-0751-4e2f-85f0-0da293a53fbf">

user1 이 이긴 상황에 기대값

<img width="470" alt="image" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/101040879/5a078758-f232-4fd8-abaa-3cf6ed4c26d2">


<img width="470" alt="image" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/101040879/a794725f-b3cb-4987-9368-3e4a0894cc60">

인메모리 값, hoslim의 승리만 반영

<img width="533" alt="image" src="https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/101040879/538823e5-b208-4593-bdc9-53834c45f98a">

이 상태로 game_record game_channel 은 잘 반영이 되지만 유저는 위 인메모리에 userIdx 꺼내서 데이터베이스에 갱신함.
