### ISSUE TITLE
MAIN_CHAT_1

### ISSUE THREAD

**Issue by wochae** [Gaepo-transcendance-fighters/BACK-END#5]
## [ ✒️  첫 메시지 입장 ]
* MAIN_CHAT_1 
첫 메시지를 보내면서 DM 방을 만드는 기능을 구현한다.

- [x] Post 구현

---

## [ 📄 상세 내용 ]
* METHOD : POST
* URL : /chat/dm/:target_nickname
* request body
{
  target_nicname,
  content,
}
* response body
{ } / OK

**Comment by wochae** [comment]
아직 끝나지 않았다.
남은 것:
레포지토리 인젝션 방식 고려,
방 생성할 때 파라미터 추가,
DTO 설정,
enum class 진행 중 고려..!,
POST 구현 ( 채널 만들고, 참여자 넣어서, 그 채널에 대한 메시지 보내기 )

**Comment by jae-hwan-kim** [comment]
request body 내용 수정
{
  target_nickname,
  content
}
에서 아래로 수정
{
  content
}

**Comment by jae-hwan-kim** [comment]
### db 연동 과정에서 에러 발생
* wochae 개발 환경에서는 db 연동이 잘됐지만, jaekim 개발 환경에서는 에러가 발생했다.
A 방식으로 했을 때 에러가 발생했고, B 방식으로 했을 때 에러가 없어졌다. 이를 보아 노드의 환경변수 (process.env) 와 관련된 부분에 문제가 있는 것 같다.

![image](https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/85930183/4f41e93c-d95a-43eb-85b9-346fdd89a94d)

A 방식에서 다음과 같은 에러 발생.
![image](https://github.com/Gaepo-transcendance-fighters/BACK-END/assets/85930183/3ba76e5a-e18c-4bb3-b0c5-709876a50a75)

B 방식은 보안상 이슈가 생길 수 있기 때문에 바꿔야함. A 방식을 할 수 있게 수정을 할지, 다른 방식을 사용할지 고민하자.
